#!/bin/sh

set -e

lb config noauto \
	--distribution wheezy \
	--archive-areas "main contrib non-free" \
	--mirror-bootstrap http://ftp.debian.org/debian \
	--mirror-chroot http://ftp.debian.org/debian \
	--mirror-chroot-updates http://ftp.debian.org/debian \
	--mirror-chroot-security http://security.debian.org \
	--mirror-binary http://ftp.debian.org/debian \
	--mirror-binary-updates http://ftp.debian.org/debian \
	--mirror-binary-security http://security.debian.org \
	--architecture amd64 \
	--linux-flavours amd64 \
	--binary-images hdd \
	--apt-recommends false \
	--firmware-chroot true \
	--cache-packages false \
	--iso-application "Overclockix" \
	--iso-preparer "mbentley" \
	--iso-publisher "Overclockix Live project; http://www.overclockix.com; mbentley@overclockix.com" \
	--iso-volume "Overclockix" \
	--bootappend-live "boot=live config quiet splash persistence" \
	"${@}"
