#!/bin/bash

# set variables
ver_num=${1}
base_src="/opt/live/overclockix"
base_dest="/mnt/overclockix"

# check for version number
if [ -z ${ver_num} ]
then
	echo "error: you must provide a valid version number for the first argument"
	echo "example:  ${0} 7.0.0"
	exit 1
fi

### i386_iso-hybrid
arch="i386"
img_type="iso-hybrid"
dest_dir="${base_dest}/${arch}"

cd ${base_src}/${arch}_${img_type}
echo -e "\ncopying ${arch}, ${img_type}, '${ver_num}' image to '${dest_dir}'...";
cp binary.hybrid.iso ${dest_dir}/overclockix-${arch}-${ver_num}.iso
ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.iso


### i386_usb-hdd
arch="i386"
img_type="usb-hdd"
dest_dir="${base_dest}/${arch}"

cd ${base_src}/${arch}_${img_type}
echo -e "\ncopying ${arch}, ${img_type}, '${ver_num}' image to '${dest_dir}'...";
cp binary.img ${dest_dir}/overclockix-${arch}-${ver_num}.img
ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.img


### amd64_iso-hybrid
arch="amd64"
img_type="iso-hybrid"
dest_dir="${base_dest}/${arch}"

cd ${base_src}/${arch}_${img_type}
echo -e "\ncopying ${arch}, ${img_type}, '${ver_num}' image to '${dest_dir}'...";
cp binary.hybrid.iso ${dest_dir}/overclockix-${arch}-${ver_num}.iso
ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.iso


### amd64_usb-hdd
arch="amd64"
img_type="usb-hdd"
dest_dir="${base_dest}/${arch}"

cd ${base_src}/${arch}_${img_type}
echo -e "\ncopying ${arch}, ${img_type}, '${ver_num}' image to '${dest_dir}'...";
cp binary.img ${dest_dir}/overclockix-${arch}-${ver_num}.img
ls -l ${dest_dir}/overclockix-${arch}-${ver_num}.img


echo -e "\ndone."
