#!/bin/bash

### set global variables (modify for your build environment)
basedir="/opt/live/overclockix"

### i386_iso-hybrid
arch="i386"
img_type="iso-hybrid"

cd ${basedir}/${arch}_${img_type}
echo -e "\nexecuting build for ${arch}, ${img_type}...";
./build.sh
echo -e "\n\e[01;32mbuild for ${arch}, ${img_type} complete! \e[00m"; echo -ne '\007'; sleep 1; echo -ne '\007'; sleep 1; echo -ne '\007'; echo -n "press enter to continue..."; read


### i386_usb-hdd
arch="i386"
img_type="usb-hdd"

cd ${basedir}/${arch}_${img_type}
echo -e "\nexecuting build for ${arch}, ${img_type}...";
./build.sh
echo -e "\n\e[01;32mbuild for ${arch}, ${img_type} complete! \e[00m"; echo -ne '\007'; sleep 1; echo -ne '\007'; sleep 1; echo -ne '\007'; echo -n "press enter to continue..."; read


### amd64_iso-hybrid
arch="amd64"
img_type="iso-hybrid"

cd ${basedir}/${arch}_${img_type}
echo -e "\nexecuting build for ${arch}, ${img_type}...";
./build.sh
echo -e "\n\e[01;32mbuild for ${arch}, ${img_type} complete! \e[00m"; echo -ne '\007'; sleep 1; echo -ne '\007'; sleep 1; echo -ne '\007'; echo -n "press enter to continue..."; read


### amd64_usb-hdd
arch="amd64"
img_type="usb-hdd"

cd ${basedir}/${arch}_${img_type}
echo -e "\nexecuting build for ${arch}, ${img_type}...";
./build.sh
echo -e "\n\e[01;32mbuild for ${arch}, ${img_type} complete! \e[00m"; echo -ne '\007'; sleep 1; echo -ne '\007'; sleep 1; echo -ne '\007'; echo -n "press enter to continue..."; read


echo -e "\ndone."
