#!/bin/sh

set -e

lb config noauto \
	--distribution wheezy \
	--archive-areas "main contrib non-free" \
	--architecture i386 \
	--linux-flavours 486 \
	--binary-images hdd \
	--apt-recommends false \
	--firmware-chroot true \
	--cache-packages false \
	--iso-application "Overclockix" \
	--iso-preparer "mbentley" \
	--iso-publisher "Overclockix Live project; http://www.overclockix.com; mbentley@overclockix.com" \
	--iso-volume "Overclockix" \
	--bootappend-live "boot=live config quiet splash persistence" \
	"${@}"
